changesetBaseRefs:
  - master
  - origin/master
  - upstream/master

changesetIgnorePatterns:
  - "**/*.test.{js,ts}"
  - "**/*.spec.{js,ts}"

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com/"

supportedArchitectures:
  cpu:
    - current
  os:
    - current

unsafeHttpWhitelist:
  - 0.0.0.0

yarnPath: .yarn/releases/yarn-4.5.1.cjs
